### ISSUE TITLE
using ui-mask with other directives (like a capitalize directive)

### ISSUE THREAD

**Issue by armyofda12mnkeys** [angular-ui/ui-mask#101]
I was using the old ui-mask (before it depreciated/moved into angular-ui). 
I combined ui-mask with a capitalize-all directive (so as you type 800foobar, it auto-caps it to 800FOOBAR). But now that code doesn't work (the capitalize-all directive runs at the end of the mask but doesn't capitalize as you type). Any idea how to fix?

My html code is pretty simple below:
```
<input type="text" id="phone_number" ng-model="myInput.phone" 
capitalize-all
ui-mask="(***)***-****" ui-mask-placeholder ui-mask-placeholder-char="_"
autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" />
```
and matching directive:
```
'use strict';
angular
.module('myApp')
.directive('capitalizeAll', ['$filter', function ($filter) {
    return {
        require: 'ngModel',
        link: function (scope, element, attrs, controller) {
            controller.$parsers.push(function (value) {
                var transformedInput = $filter('capitalizeAll')(value);
                if (transformedInput !== value) {
                    var el = element[0];
                    el.setSelectionRange(el.selectionStart, el.selectionEnd);
                    controller.$setViewValue(transformedInput);
                    controller.$render();
                }
                return transformedInput;
            });
        }
    };
}]);
```

**Comment by lukepfeiffer10** [comment]
Have you considered using the `$formatters` array to modify the view value instead of the `$parsers` array. I believe `$formatters` are supposed to be used to modify the value from the model to the view.

Essentially, you have a `$parser` to handle `view -> model` data manipulation and `$formatters` for `model -> view` data manipulation.

**Comment by dinodujmovic** [comment]
The solution that worked for me was:

ui-options={"allowInvalidValue" : true}
