### ISSUE TITLE
Mask of 19

### ISSUE THREAD

**Issue by MathewBerg** [angular-ui/ui-mask#103]
If you use a mask of 19, it will show this in the input:

`1_`

If you enter a number such as 8:

`18`

The model will be updated to 8

If you enter the number 1:

`11`

The model never gets updated, although it should return a 1. You can see this on the demo page by using the mask of 19 and trying to enter a 1 or a 2. Also it seems that any letter/number you use with the number followed by it doesn't work. So 19 won't work for a mask, but 91 will. Same thing with aA not working, also Aa seems to glitch out and always puts in aa. If I should be using a different masking solution please let me know.

Other thing of note, if you use the keyboard to delete back and replace the last character with a 1 it won't work. BUT if you highlight the last character and change it to a 1 it will work as expected and my model will be 1.

I'm using chrome.

**Comment by lukepfeiffer10** [comment]
Thanks for pointing out this issue. It appears to be a slightly complicated issue dealing with some core functionality. Hopefully, I will be able to get a fix in place in the next day or two.
