### ISSUE TITLE
Mask autocompletes with unwanted numbers

### ISSUE THREAD

**Issue by rdehuyss** [angular-ui/ui-mask#108]
Hi, I like this masking lib but it has a serious bug. If I enter the mask for a Belgian Social Security Number, the mask autocompletes the input with rubbish :unamused: 

- Open new browser
- go to https://htmlpreview.github.io/?https://github.com/angular-ui/ui-mask/master/demo/index.html
- enter the mask 99.99.99-999.99
- go to the input field and start typing:
    811 => this changes the value of the mask to 81.11.11-__.__
    8110 => value is now 81.10.11-10.11

reproducable in Firefox and Chrome.

Any idea what is happening?

**Comment by lukepfeiffer10** [comment]
I'm sure this is related to a rather large change I recently made in #107. It passed all the tests we currently have but clearly there are more tests needed. 

I'll look into this right away but in the meantime if you can get the version prior to that found in #107 the library should work for you.

Maybe @PowerKiKi can roll that back or maybe I just have to submit a PR with it reverted...

Thanks for submitting the issue.

**Comment by rdehuyss** [comment]
I rolled back to 1.7.0 and that works great!

**Comment by lukepfeiffer10** [comment]
Great! Sorry about that inconvenience. I have a fix on the way so thanks again for finding that issue (I forgot to account for identical mask components in a mask...).

**Comment by PowerKiKi** [comment]
Fixed in 1.7.2, thanks to all of you.
