### ISSUE TITLE
Using mask for uppercase characters

### ISSUE THREAD

**Issue by bolemeus** [angular-ui/ui-mask#113]
I want to use the mask for dutch zipcodes.

For this I use the following html

```
<input class="form-control input-sm" type="text" name="adresZipcode" ng-model="adres.zipcode"
placeholder="Zipcode" required ng-pattern="/^[0-9]{4}\s?[a-zA-Z]{2}$/" ui-mask="9999 AA"
ui-options="maskOptions" ui-mask-placeholder ui-mask-placeholder-char="_" />
```

Im overriding the maskOptions with following.

```
    $scope.maskOptions = {
        maskDefinitions : {
            '9': /\d/, 'A': /[A-Z]/
        }
    };
```

This works, but I also want the input to accept lowercase characters. It should be smart enough to figure out that those need to be transformed to uppercase characters. Can I accomplish this with this library or do I need to write an additional directive?

**Comment by lukepfeiffer10** [comment]
Currently this library does not have the functionality of automatically capitalizing characters. I think this could be pretty easily done with an uppercase [filter](https://docs.angularjs.org/api/ng/filter/uppercase).

**Comment by daric81** [comment]
I think this would be a great additional feature for this library.

**Comment by PowerKiKi** [comment]
@daric81 since there is no active "core" developers anymore, I think it would be best to submit a PR implementing what you want instead of keeping a list of things to do with nobody doing it
