### ISSUE TITLE
 ui-mask with uib-typeahead

### ISSUE THREAD

**Issue by lfjaimesb** [angular-ui/ui-mask#114]
good afternoon.

I'm trying to use both directive (ui-mask and uib-typeahead), but I can not enable both, any suggestions?

`<input type="text" ui-mask="999-99-999" ng-model="selected" uib-typeahead="cuenta as cuenta.clave for cuenta in cuentas | filter:$viewValue | limitTo:8" class="form-control">`

**Comment by lukepfeiffer10** [comment]
I think your issue stems from the filter on the typeahead `filer:$viewValue`. The ui-mask directive sets the `$viewValue` property as part of its main functionality. This is what causes the input to appear like so `___-__-___` and `123-__-___` after entering some text. Which I assume those kind of values would match nothing in your set of values to filter.

Currently there is no way with the ui-mask directive to have access to the un-masked value if it is invalid (i.e. `123-__-___` is invalid based on the mask). This means that the un-masked value of `123` is never exposed outside of the directive meaning there is no way to pass it into the `filter` functionality of the typeahead directive. There has been previous discussion on allowing invalid entries update the `$modelValue` of `ngModel` which would then make the un-masked value usable in the typeahead filter via `filter: selected` in your case. However, this has not been implemented yet although it would be a relatively easy change if there is enough interest.

**Comment by lfjaimesb** [comment]
If I assumed it was some $viewValue, it's just my first project with AngularJS so I have little experience with the environment, so I took some work to find where to make changes, but finally I got it, and I share in case you want to add to the repository, really I do not know how to add it and if I have permission or not, if someone wants to tell me how to do it, we will gladly continue to participate in adding new features gradually.

In the **mask.js** file in the function **validateValue** change the following line

`return value.length ? value.length >= minRequiredLength : true ;`

by

`return !iAttrs.uibTypeahead ? ( value.length ? value.length >= minRequiredLength : true ) : true;`

because the parse function is validated and if one fails the validation is sent undefined and therefore not typeahead into operation until it is completed to fill the entire field,  if I'm wrong I would appreciate corrected

Only I have the **ui-bootstrap-tpls.js** file so the "UibTypeaheadController" controller, function getMatchesAsync within $ q.when (parserResult.source (originalScope, locals)). Then (function (matches) {.... }
`change the following line var onCurrentRequest = inputValue === modelCtrl.$viewValue;`.

by these lines

```
var vValue = modelCtrl.$viewValue;

if(attrs.uiMask){
    vValue = vValue.replace(/[_|-]/g,"");
}

var onCurrentRequest = inputValue === vValue;
```

not if the changes I have explained well or not, but it works so far.

Regards.

**Comment by lukepfeiffer10** [comment]
After looking over what you have done so far, I would highly recommend not changing the source code of either of those libraries to have checks determining if your element contains both of those directives.
 
Let me see if I can put together something in a plunkr for you.
