### ISSUE TITLE
Include mask chars in value

### ISSUE THREAD

**Issue by dandanknight** [angular-ui/ui-mask#116]
Hi, is it possible to include the mask character in the final model value?

For instance, if I have an input like this....

`
<input ui-mask="9:99" ng-pattern="/^[0-5]:[0-5][0-9]$/" ng-model="vm.title.displayRuntime">
`

...then the output, for example is "123", whereas I'd like it to be "1:23", including the character that is specified in the mask.

Is there an easy way of doing this do you know?

Many thanks.

**Comment by dandanknight** [comment]
Actually, I think I've sussed it by finding the undocumented option of `model-view-value="{{true}}"` by searching though the demo code.

**Comment by PowerKiKi** [comment]
Should be solved by #117
