### ISSUE TITLE
Cannot set global config

### ISSUE THREAD

**Issue by mackski** [angular-ui/ui-mask#120]
Tried global config and also part of app.run however I always get the message:
Error: [$injector:unpr] Unknown provider: uiMask.ConfigProvider

Angular 1.4.3

Works without global config.

**Comment by PowerKiKi** [comment]
Try with the brand new 1.8.0 and it should work.

**Comment by mackski** [comment]
Indeed it's fixed, however this two options cannot be set in global config:
uiMaskPlaceholder
uiMaskPlaceholderChar

**Comment by lukepfeiffer10** [comment]
@mackski Those as well as `modelViewValue` should probably be part of that global config object but for now if you need them they can be used as attributes on an individual input element. I'll look into adding them to the global config later.
