### ISSUE TITLE
Nuget

### ISSUE THREAD

**Issue by ashwin027** [angular-ui/ui-mask#124]
Is there any way, we can make this library available on nuget?

**Comment by lukepfeiffer10** [comment]
I think that would be a bad decision as even Microsoft has recommended using bower/npm for JS package management in Visual Studio. [Source](http://www.hanselman.com/blog/IntroducingGulpGruntBowerAndNpmSupportForVisualStudio.aspx)

Also, npm is fully supported in Visual Studio as of 2015. [Source](http://webtooling.visualstudio.com/package-managers/npm/)
