### ISSUE TITLE
Support for multiple masks in one input

### ISSUE THREAD

**Issue by matyax** [angular-ui/ui-mask#125]
We have a situation where we need to support masks for credit cards, which are:
* 9999-999999-99999
* 9999-9999-9999-9999

Is it possible to support multiple masks in the same input? I found no reference in the docs.

**Comment by lukepfeiffer10** [comment]
I'm not sure what your exact use case is but you can assign the ui-mask attribute to a variable and then have that variable change to whichever mask you need based on the credit card type.

The demo page uses this to allow for dynamic mask generation.

````html
<input class="form-control" id="masked" name="masked" ui-mask="{{y}}"

**Comment by matyax** [comment]
That may help, it's a rather odd use case the one I'm working on.
Thanks for the feedback.

**Comment by jewpaltz** [comment]
ui-mask="{{y}}" does not work. It actually seams to be evaluated once on page load, but not again after that

**Comment by LukasBeaton** [comment]
Hey @jewpaltz,

Did you end of finding a solution to this?

I am experiencing a similar issue with the "model-view-value" attribute for the ui-mask directive. The attribute "ui-mask" itself is being updated property for me. I am using ui-mask version 1.8.2 on an older project.
