### ISSUE TITLE
Clear default maskDefinitions

### ISSUE THREAD

**Issue by Sir-J** [angular-ui/ui-mask#126]
How do I change maskDefinitions for a single item? 
If i write: 

> uiMaskConfig.maskDefinitions({'?': /0-9]/});

result mask

> '9': /\d/,
> '?': /\d/,
> 'A': /[a-zA-Z]/, 
> '*': /[a-zA-Z0-9]/
>

**Comment by lukepfeiffer10** [comment]
@Sir-J The readme includes explanation about how to customize the `maskDefinitions` for a single element and globally. If that doesn't help, then I need more information about what you are trying to do in order to help solve your issue.

Also, using a `?` as an character in mask definitions will most likely cause issues as the `?` is interpreted as the optional mask character flag.

**Comment by Sir-J** [comment]
elatively? I understood you. Tomorrow I'll try to adjust to a different character.
Today, I am doing so:

In control:
```
$scope,phone = "";
$scope.uiMaskConfig = { 
        maskDefinitions({'?': /0-9]/});
};
```
In view:
`
<input ui-mask="+7 (9??) ???-??-??" ui-options="uiMaskConfig" ng-model="phone">
`
After start app i see:
![ui-mask](https://cloud.githubusercontent.com/assets/12563410/13402993/03076d0c-df3d-11e5-8a6d-e6b808aea1f6.png)

If I comment out this line in iu-utils.js:
`angular.extend(current[i], original[i]);`
ui-mask working correct.
![ui-mask_correct](https://cloud.githubusercontent.com/assets/12563410/13403319/96846aac-df3e-11e5-8e87-b556cf080a34.png)

**Comment by lukepfeiffer10** [comment]
Ah okay, well it looks like you are using a very old version of ui-mask if it is still in ui-utils.js which might be part of the problem.

If you want to redefine the entire `maskDefinitions` on an individual element, then you would need to set each key from the defaults to `undefined` and then define the character you want.

Example:
````javascript
maskDefinitions: { 
      '9': undefined,
      'A': undefined,
      '*': undefined,
      '[YOUR_CHAR]': /[0-9]/
} 
````

However, I am not sure if that will work with your version of the ui-mask library. I would recommend getting the latest version first.

**Comment by Sir-J** [comment]
Thank you, I will do so today.
