### ISSUE TITLE
how can I unMask when focus and remask when blur

### ISSUE THREAD

**Issue by son0nline** [angular-ui/ui-mask#128]
Hi everyone,
how can I unMask when focus and remask when blur?

**Comment by lukepfeiffer10** [comment]
That is not a current functionality in this library.

**Comment by son0nline** [comment]
so can I do that by other way?

**Comment by lukepfeiffer10** [comment]
You can make a directive that utilizes the ui-mask filter from this issue #31 when the blur event occurs to mask the input value and then if the element is focused you would have to unmask the value.

**Comment by chesminsky** [comment]
just css it
`input:not(:focus) {
	@include placeholder {
		color: transparent;
	}
}`
its a mixing for sass in this example
