### ISSUE TITLE
Angular Material with ui-mask

### ISSUE THREAD

**Issue by waldandrade** [angular-ui/ui-mask#130]
With this .... 

//if ( ! originalPlaceholder) {
//    iElement.attr('placeholder', maskPlaceholder);
//}

I got this working fine!! Cause Angular Material input gets previous label to placehold the field with great style.

**Comment by lukepfeiffer10** [comment]
I'm not sure why you opened this issue. Is there an issue? If so, what is it?

**Comment by waldandrade** [comment]
Sorry ... i was not clear!

This is a incompatibility issue. If i download this plugin, and install in my modular app, this block breaks the modular layout .. 

Modular uses label to create placeholder, but this block forces a creation of a poor placeholder with mask value.

I sugest that you change this in the new version, cause no one needs the mask as placeholder. :D

**Comment by lukepfeiffer10** [comment]
I'll look into providing an option for this functionality (ui-mask not adding the placeholder) but completely removing it could cause issues for people relying on this feature to have a placeholder.

**Comment by waldandrade** [comment]
The problem is that if i say to directive that want no placeholder, so i think the directive couldn't force this.

But i just wanted to help! thanks

**Comment by lukepfeiffer10** [comment]
@waldandrade Try out the new config option `addDefaultPlaceholder` and let me know if that works for you.
