### ISSUE TITLE
uiMask.ConfigProvider not working

### ISSUE THREAD

**Issue by tbhasme** [angular-ui/ui-mask#135]
The `maskDefinitions `method is not present on the `uiMask.ConfigProvider`

This is a snippet from the documentation

```
app.config(['uiMask.ConfigProvider', function(uiMaskConfigProvider) {
  uiMaskConfigProvider.maskDefinitions({'A': /[a-z], '*': /[a-zA-Z0-9]/});
}
```

However in `dist/mask.js` there is no such method present. Also there is no example for using the `ui-options` directive.

Can you guide me as to how I can specify a custom mask definition.

**Comment by lukepfeiffer10** [comment]
@Lefka worked on the config provider addition maybe he can give insight on that part.

The `ui-options` attribute works like any normal html attribute except you provide it a JSON string with the options you wish to override specified as key/value pairs.

```html
<input type="text" ui-mask="999-999" ui-options="{clearOnBlur: false}" />
```

**Comment by RafaelTaranto** [comment]
@lukepfeiffer10 Looks like the method is actually missing, also the following test does not change the clearOnBlurPlaceholder, only checks the default value. 

```
 it("should merge default values with configured values", inject(function($injector) {
      uiMaskConfigProvider.clearOnBlur(false);
      uiMaskConfigProvider.addDefaultPlaceholder(false);
      var service = $injector.invoke(uiMaskConfigProvider.$get);
      expect(service.clearOnBlur).toEqual(false);
      expect(service.clearOnBlurPlaceholder).toEqual(false);
      expect(service.addDefaultPlaceholder).toEqual(false);
    }));
```

I think i can PR later today if @Lefka doesn't respond to this.

**Comment by RafaelTaranto** [comment]
@tbhasme You can specify a custom mask definition using the `ui-options`. I'm not really sure on how insert the regex directly into the html, but you can set a variable in the controller and use it in the ui-options.

```javascript
$scope.options = {maskDefinitions: {'7': /\d/}};
```


```html
<input type="text" ui-options="options" name="myPhone"  ui-mask="(777) 777-7777" 
```

**Comment by lukepfeiffer10** [comment]
Should be fixed in v1.8.3 from PR #138

**Comment by robson-jardim** [comment]
It's working in v1.8.3!!!

MY HTML:
<input type="text"
       ng-model="redeemCodeGet.text"
       ui-mask="***-***-***"
       ui-mask-placeholder
       ui-mask-placeholder-char="_"
       ui-options="options" >

MY ANGULARJS CONTROLLER:
$scope.options = {maskDefinitions: {'*': /./}}; //To accept all char

**Comment by TTNarendran** [comment]
can I call a function in ui-mask .Kindly let me know asap
example
<input type="text" ui-options="options" name="myPhone"  ui-mask="controller.myfun()"
