### ISSUE TITLE
ui-mask-placeholder-char:" " has no effect

### ISSUE THREAD

**Issue by PavelPolyakov** [angular-ui/ui-mask#136]
Hi,

Even when I do:
![image](https://cloud.githubusercontent.com/assets/839290/13885389/708cc784-ed32-11e5-9777-aff27d8932ba.png)

I still have the mask on the screen:
![image](https://cloud.githubusercontent.com/assets/839290/13885398/7cb79d4a-ed32-11e5-806c-6450fddb6737.png)

Same happens on the demo page:
https://htmlpreview.github.io/?https://github.com/angular-ui/ui-mask/master/demo/index.html

It would be nice to hide the placeholder, I think.

Regards,

**Comment by lukepfeiffer10** [comment]
You can use the config option `addDefaultPlaceholder=false` to remove the default placeholder functionality for the library. This can be done on an individual element using the `ui-options` attribute or by using the global config settings as described in the readme.

**Comment by PavelPolyakov** [comment]
I have done that, it removes the placeholder indeed. However, when I start to type - the placeholder is in place again. While nothing is in the field and focus is not in the input - there is no placeholder there.

**Comment by lukepfeiffer10** [comment]
That functionality is pretty much the entire purpose of this library. To give a user a "mask" for how the input should be entered. I'm not sure what you are trying to use this library for if not for that purpose.

**Comment by PavelPolyakov** [comment]
Correct,

but according to the documentation, we have this option: 
`uiMaskPlaceholderChar`
> Allows customizing the mask placeholder character. The default mask placeholder is _.

I want to set this option to be the space. I think it's still logical, that it would just draw the space instead of the `_`, or any other placeholder char I can set (it works perfectly with any of `#!@#$abcd`). I think it would still look cool and convenient for the end user if we show him the mask with the space as placeholder.

The library is perfect and works like a charm, I just thought that this particular thing goes in spite of the documentation.

Regards,

**Comment by lukepfeiffer10** [comment]
Okay I can look into why the space character is not working as a valid `uiMaskPlaceholderChar`.

Thanks!

**Comment by lukepfeiffer10** [comment]
@PavelPolyakov I had some more time to look into this and found the issue. If you want to set the `uiMaskPlaceholderChar` as a `space` character, then you need to set the `uiMaskPlaceholderChar` attribute to the word `space`.

```html
<input type="text" ui-mask="999-999" ui-mask-placeholder-char="space" ...
```

This is mentioned in the demo page but is not documented well in other places.

**Comment by PavelPolyakov** [comment]
@lukepfeiffer10 
Thanks, man! That really helps!

Sorry for me being not enough attentive :)

**Comment by lukepfeiffer10** [comment]
No worries. I try to take note of these semi hidden facets of the library so they can be documented in the readme so thanks for mentioning this.

**Comment by judsonmusic** [comment]
Is there anyway to set this globally?

**Comment by lukepfeiffer10** [comment]
Not currently.

**Comment by raphaeloneves** [comment]
> <input type="text" ui-mask="999-999" ui-mask-placeholder-char="space" ...

Nice! This is exactly what I was looking for. Tks

**Comment by goiabetks** [comment]
> <input type="text" ui-mask="999-999" ui-mask-placeholder-char="space" ...

Nice!
