### ISSUE TITLE
keep value after lost focus.

### ISSUE THREAD

**Issue by LuanNg** [angular-ui/ui-mask#14]
I make ui-mask for phone number, i want to keep value to validate when user click to next item while value still show for user. how  ui-mask support this?

thanks,
Luan

**Comment by PowerKiKi** [comment]
I don't understand what you mean. Maybe step-by-steps and/or screenshot would help

**Comment by LuanNg** [comment]
you are inputting a value in MAC address 1.

![2015-07-10_131203](https://cloud.githubusercontent.com/assets/12404031/8613125/7167de30-2705-11e5-8e5b-ff423eec5016.jpg)

then you click to other inputbox, the value is disappear, i want to keep the value of MAC Address 1, please advice

![2015-07-10_131249](https://cloud.githubusercontent.com/assets/12404031/8613124/7165da18-2705-11e5-823b-6a77e73ee458.jpg)

**Comment by NickTomlin** [comment]
@LuanNg This is configurable via the `clearOnBlur`setting in the [`uiMaskConfig`](https://github.com/angular-ui/ui-mask/blob/master/src/mask.js#L11). You can set it in the `config` block of your module like so:
```javascript
angular
  .module('myApplication')
  .config(function (uiMaskConfig) {
    uiMaskConfig.clearOnBlur = false;
  });
```

**Comment by LuanNg** [comment]
it works, thanks!

**Comment by leitasat** [comment]
@NickTomlin could you please write it somewhere at homepage or at repo's Readme?

**Comment by DaAwesomeP** [comment]
@NickTomlin this doesn't work for me. I get an error `Unknown provider: uiMaskConfig`.

**Comment by NickTomlin** [comment]
@DaAwesomeP it sounds like UI Mask is not being included as a dependency of your module. My snippet above did not include ui mask as a dependency of the example application; i've updated it to correct this.

**Comment by DaAwesomeP** [comment]
@NickTomlin I'm doing that in my app. If I wasn't, then the mask wouldn't work at all. I'm using Angular v1.4.8 by the way.

**Comment by NickTomlin** [comment]
@DaAwesomeP hmm, i'm not sure what is going :\. Can you recreate this issue in a fiddle?

**Comment by DaAwesomeP** [comment]
Here you go: http://plnkr.co/edit/jgD71cHdz9ydSjHQjsGy?p=preview
If you comment out the config block in `app.js`, then the mask works fine.

**Comment by NickTomlin** [comment]
@DaAwesomeP ack, it is definitely my fault. `uiMaskConfig` is a `value` which is not accessible in a `config` block. Change `.config` to `.run` and you should be good to go. I've updated my example as well.

**Comment by DaAwesomeP** [comment]
Great, It works!
