### ISSUE TITLE
Cursor issues on Samsung Galaxy s5, and Nexus 6

### ISSUE THREAD

**Issue by mryarbles** [angular-ui/ui-mask#141]
Just discovered that there are major issues on our Android devices.  

Using 
ui-mask="(999) 999-9999"
ui-options="{clearOnBlur:false}"

or

ui-mask="99-99-9999"

The cursor seems to get stuck after the first digit you enter. If you select a new position, it will get stuck again after you enter another digit. 

This is very very broken.

Unfortunately, we're using this directive in about a dozen places in our forms :(

**Comment by mryarbles** [comment]
Update: When I switch the keyboard from Samsung Keyboard to Google Keyboard, Google's keyboard works with no issue. I looked on the Nexus device and it was using a custom keyboard.

**Comment by lukepfeiffer10** [comment]
I and others have seen this issue many times and the fix I have found is to disable the `input` event in the `eventsToHandle` array. This can be done using the config provider as documented in the readme.

This fix should probably be mentioned in the readme as well as it is a common issue. Hopefully I can add it soon.

Let me know if this solution works for you.

**Comment by kaiocb** [comment]
@mryarbles: in samsung devices smart typing will mess up you inputs but this may help you in custom keyboards in other devices as @lukepfeiffer10 said:

```
App.run(['uiMaskConfig', function (uiMaskConfig) {

    var isAndroid = /(android)/i.test(navigator.userAgent);

    if (isAndroid) {
        var index = uiMaskConfig.eventsToHandle.indexOf('input');
        uiMaskConfig.eventsToHandle.splice(index, 1);
    }
}]);
```

**Comment by lukepfeiffer10** [comment]
Also, @kaiocb with the newest version of the library you don't have to use the `run` function to change the `uiMaskConfig` object as there is now a `uiMaskConfigProvider`. The run functionality is still preserved but the config provider is more standard and hopefully easier to use.
