### ISSUE TITLE
Can't use with input type="number"

### ISSUE THREAD

**Issue by alejandromagnorsky** [angular-ui/ui-mask#145]
Got this error message in Google Chrome:
`Error: Failed to read the 'selectionStart' property from 'HTMLInputElement': The input element's type ('number') does not support selection.`

**Comment by lukepfeiffer10** [comment]
`ui-mask` wasn't designed to work on inputs of type number. Also, I doubt there would be a way to make it work either because of the limited valid characters for a number input.

**Comment by traviskindred** [comment]
Workaround I'm using is to use type tel. That gives the benefit of numeric input on touch input devices, but it breaks validation.

**Comment by alejandromagnorsky** [comment]
Cool, that seems to work fine. Thanks @traviskindred !
