### ISSUE TITLE
Support module systems (UMD, or at least CommonJS)

### ISSUE THREAD

**Issue by pmowrer** [angular-ui/ui-mask#15]
Perhaps via https://github.com/bebraw/grunt-umd

**Comment by PowerKiKi** [comment]
We don't use grunt, but gulp. If you submit a PR, I would merge it, but I don't know enough about UMD to do that by myself

**Comment by Tim91084** [comment]
Submitted a pull request for this #59.

**Comment by Tim91084** [comment]
We can close this one, right?
