### ISSUE TITLE
Anyway to check/listen if user paste data from clipboard?

### ISSUE THREAD

**Issue by fmiboy** [angular-ui/ui-mask#151]
For example lets say I have following mask:

BC - * * * * - * * *

When user paste clipboard text BC-12AF-FGH it skips last GH part and starts pasting from 3rd char and output becomes BC-BC12-AFF. 
Is there any way to fix this?
I tried to use ng-paste and update ng-model value, but didn't work.

**Comment by lukepfeiffer10** [comment]
Just make sure to select all in the field before pasting values if you want to overwrite what is already in the field.

**Comment by fmiboy** [comment]
It worked, but any other way to work around without selecting all in the field?
thanks

**Comment by lukepfeiffer10** [comment]
Expected functionality for pasting content is for that content to begin where the cursor is in the field. I would guess then that moving the cursor to be before the already entered content would cause that content to be removed if your pasted value is >= the length of the mask.
