### ISSUE TITLE
Is it possible to format numbers with commas?

### ISSUE THREAD

**Issue by zalohcin** [angular-ui/ui-mask#152]
I am trying to figure out if it is possible to format numbers with commas.

Example: 
1000 => 1,000
1000000 => 1,000,000

Using "999,999,999" results in "100,0__,___"  while "___,__1,000" would be ideal.

I believe the simple solution would be to add an option where we can right align the input.

Is this or some other solution possible?

**Comment by lukepfeiffer10** [comment]
If all you want to do is add number separators it is rather simple to do with a custom directive; however, this directive does not provide the functionality you are looking for nor does it make sense to add it to this directive.
