### ISSUE TITLE
Value of zero not displayed

### ISSUE THREAD

**Issue by thrilleratwork** [angular-ui/ui-mask#166]
https://github.com/angular-ui/ui-mask/blob/master/dist/mask.js#L92

The isEmpty check does not properly check for a value of zero.  For my needs, I changed the check using lodash's isUndefined function:
```
return originalIsEmpty(unmaskValue(_.isUndefined(value) ? '' : value));
```
I am sure this could be changed to:
```
return originalIsEmpty(unmaskValue(value || value === 0 ? value : ''));
```

However, I do not know if this would impact other masks.

**Comment by lukepfeiffer10** [comment]
I'm not sure what your use case is but the `unmaskValue` function looks like it would always return a string so I'm not sure how you are event getting `value === 0` to be true...

**Comment by thrilleratwork** [comment]
The unmaskValue function is not the issue but how value is passed into it.  "||" evaluation is the same as "==" which for [the integer value zero is evaluated falsey](http://zero.milosz.ca/).  

As a test, in your browser console, run 

```
console.log(1||'')
```
and 

```
console.log(0||'')
```

The integer '1' is printed for the first, but an empty string is printed for the second because 0 == false.  For my use case, the default value is integer zero but it is not displayed in the view.

**Comment by lukepfeiffer10** [comment]
Maybe you should change your default value then considering the directive is operating under the context of strings...
