### ISSUE TITLE
Screwy Behavior With Regular Placeholder Attribute

### ISSUE THREAD

**Issue by joelcdoyle** [angular-ui/ui-mask#167]
Instead of replacing the text of a traditional `placeholder="Some Number"` attribute, which is standard input tag behavior, the placeholder is visible while typing

`<input type="text" placeholder="Some number" ui-mask="9999"/>`

https://plnkr.co/edit/wSJmnZIqnaxFTfne9vh3?p=preview

**Comment by lukepfeiffer10** [comment]
This is a weird long standing issue but to fix your problem you just have to add `ui-mask-placeholder` as an attribute on your input and then it works properly.

**Comment by joelcdoyle** [comment]
Awesome, thanks for the quick response. This does solve the issue. It does require that you have an placeholder character, though (I didn't want any placeholder char).

**Comment by lukepfeiffer10** [comment]
You can set the placeholder character as a `space` with `ui-mask-placeholder-char="space"`. There are some issues with it if you use optional mask characters because of how angular trims `$viewValue` by default. But that might get your closer to what you want.

**Comment by joelcdoyle** [comment]
Yep, that was it. I was trying to set it with 

`ui-mask-placeholder="space"`

 instead of 

`ui-mask-placeholder ui-mask-placeholder-char="space"`

**Comment by lukepfeiffer10** [comment]
Cool. Glad I could help.
