### ISSUE TITLE
WARNING: Tried to load angular more than once.

### ISSUE THREAD

**Issue by jsb8908** [angular-ui/ui-mask#173]
Using ui-mask with browserify:

var uiMask = require('angular-ui-mask');

Gives "WARNING: Tried to load angular more than once." in the browser.

If I remove this line from index.js:
var angular = require('angular');

The warning goes away and everything works fine.

Is there something I'm missing? Should angular be required in the index file like that?

**Comment by lukepfeiffer10** [comment]
Honestly not sure if it's needed... Maybe @Tim91084 can answer that as he originally created the `index.js` file.

**Comment by jsb8908** [comment]
Thanks. 
I did find a way around this in my current setup. You can tell browserify to ignore references that modules try to pull in during the bundling.

(Using Gulp):
var browserify = require('browserify');
var bundler = browserify(props);
 bundler.ignore('angular');
