### ISSUE TITLE
Mask doesn't display on focus

### ISSUE THREAD

**Issue by ermolaevalexey** [angular-ui/ui-mask#174]
I  loaded the script just as in instruction on my page.
`<script src="node_modules/angular/angular.js"></script>
<script src="node_modules/angular-ui-mask/dist/mask.js"></script>`
Also, I injected the dependency in bootstrapping function:
`angular.module('app', `['ui.mask']);

And, finally, I added ui-mask attribute to input:
`	angular.module('app')

	.directive('myInput', function() {
		return {
			require: '^myForm',
			restrict: 'E',
			transclude: true,
			scope: {
				name: '@name',
				type: '@type',
				label: '@label',
			},
			link: function (scope, el, attrs, ctrl) {
				console.log(scope.$parent.$parent);
				console.log(ctrl.user);
				var input = el.find('input');
				if (attrs.required !== undefined) {
					input.attr('required', true);
				}
				if (attrs.name === 'phone') {
                                        //here we adding the attribute
					input.attr('ui-mask', '+7 (999) 999-9999');
				}
			},
			templateUrl: '/js/partials/my-input.html'
		}
	});`

And if I focus the input, the mask doesn't appear in it.
What am I doing wrong?
Here's the repo of the project:
https://github.com/ermolaevalexey/alfamotors-test-angular

**Comment by ermolaevalexey** [comment]
Please help someone!

**Comment by lukepfeiffer10** [comment]
It doesn't work because you added the ui-mask attribute in the link function. Therefore, the ui-mask directive never gets instantiated because the attribute isn't on the element during the compile phase.

**Comment by ermolaevalexey** [comment]
Ok, I got it, but what if I have nested directives, and i need ui mask to be provided just in one (phone field) ?
