### ISSUE TITLE
Is it possible to have predefined part of masked input that goes to model?

### ISSUE THREAD

**Issue by rusekr** [angular-ui/ui-mask#178]
Hello!
I need to display all phones as mask +7 (999) 999-99-99 but have that first "7" char in result model value. But in the end I have only masked input chars as result and need to add that 7 manually before saving and cut it when loading to model. Is it possible with some configuration? Tried altering default mask regexps but no result.

edit: and another question about mask logic: Is it possible to have "10 or 12 chars" logic? Like if I have exact 10 or exact 12 digits (not 11) in my input before model can be flagged as correct

**Comment by lukepfeiffer10** [comment]
First question. `model-view-value=true` which will make the model equal the exact same value as the view.

You can use optional characters for the last two digits but it will validate as correct at 10,11, and 12 characters.

**Comment by rusekr** [comment]
Thanks for an answer!
