### ISSUE TITLE
An easier way to get masked.$viewValue?

### ISSUE THREAD

**Issue by c19** [angular-ui/ui-mask#18]
Or at least document how masked.$viewValue is attach to [and to which] controller.
I do some testing and figured out that it would attach to the outer <form> tag.
but it seems it rely on other conditions. Still trying to figure out .

**Comment by c19** [comment]
oh, I see, the input should have `id="masked" name="masked" ui-mask="xxx" ng-model="yyy"` and an outer `<form name="formname">` tag. then the formname.masked.$viewValue would show up.

It's really annoying to figure these out from demo source code. especially it's full of same named things. lots of "mask" named thing.

**Comment by PowerKiKi** [comment]
A PR for documentation would be very welcome. Or at worst at new page on the wiki.
