### ISSUE TITLE
zip code mask - 5 or 9 characters

### ISSUE THREAD

**Issue by seiyria** [angular-ui/ui-mask#186]
I can't seem to find any solutions anywhere for this particular issue. I have an app where people can enter a zip code, but they can enter either the 5 digit - ie, 12345, or they can enter the expanded form -ie, 12345-6789.

I've tried `ui-mask="{{ $ctrl.zipCode.length > 5 ? '99999-9999?' : '99999'}}"` as well as `ui-mask="99999-?9?9?9?9?"` - the latter works, but it leaves an undesirable trail of underscores at the end (as well as the dash).

**Comment by seiyria** [comment]
Well, at least this problem is out there now. I solved it a different way, using ng-pattern: `ng-pattern="/^\d{5}(-?\d{4})?$/"`

**Comment by jeanabraham** [comment]
The other option is:

HTML:

`<input type='text' ui-mask-placeholder-char="space" ui-mask='{{zipMask}}' required ng-model="zipCode" name="personZipCode" ng-change="checkZipMask()">`

JS:
 ```
   $scope.checkZipMask = function () {
        var zipCode = $scope.zipCode;
        if (zipCode && zipCode.length > 5) {
            $scope.zipMask = '99999-?9?9?9?9';
        } else {
            $scope.zipMask = '99999?9';
        }
    }
```
