### ISSUE TITLE
not working with ui-bootstrap datepicker

### ISSUE THREAD

**Issue by sibeliusseraphini** [angular-ui/ui-mask#19]
This directive is not working when the input has a datepicker directive of ui-bootstrap

**Comment by PowerKiKi** [comment]
https://angular-ui.github.io/bootstrap/#/datepicker already have some kind of mask functionality built-in. Making ui-mask no needed at all.

**Comment by settysreekanth** [comment]
@sibeliusseraphini  did you find any solution for this? i don't want to use type='date' as it is not supported by all the browsers?

**Comment by sibeliusseraphini** [comment]
@settysreekanth 

@settysreekanth: We've created a directive to handle this problem: https://gist.github.com/sibeliusseraphini/4d1275ea1f8c980dd645

I'll create a bower package when I have time

Let me know if you need any help

**Comment by settysreekanth** [comment]
@sibeliusseraphini thanks for the reply. I believe, your solution doesn't apply masking till user completes the field input or till model gets assigned.. please correct me if I am wrong?

I am actually looking at the same behavior as it works with angular-ui-mask

**Comment by sibeliusseraphini** [comment]
@settysreekanth the changeInput() and changeDP() will apply the mask, however it only support one type of mask yet, you can improve it if you want
![screenshot 2015-10-19 14 25 02](https://cloud.githubusercontent.com/assets/2005841/10583705/3b7781c4-766d-11e5-8a48-209860a1fc4d.png)

**Comment by settysreekanth** [comment]
Thanks @sibeliusseraphini .. I will try customize and use it for my requirement.

**Comment by augustbend** [comment]
@settysreekanth, I'm in a similar scenario. Did you manage to fix this? If so, could you show how you did it. Thanks!

**Comment by settysreekanth** [comment]
@augustbend Not sure if its good to give link to different library in this forum however I ended up using different masking library https://github.com/RobinHerbots/jquery.inputmask and writing my own custom directive as below
```

angular.module('my-app').directive('date-mask', function(){
  return{
    restrict: 'A',
    require: 'ngModel',
    link: function(scope, elem, attr){
      ngModel.$formatters.push(formatter);
      ngModel.$parsers.push(parser);

      function formatter(fromModelValue){
        element.val(fromModelValue);
        return element.inputmask(maskpattern).val();
      }
      function parser(fromViewValue){
        return fromViewValue;
      }

    }
  }
})
```

**Comment by engemasa** [comment]
@PowerKiKi: Could you please provide a Plunker of the masking functionality (preferably on the datepicker-popup)? Based on the documentation, I'm not seeing how this is accomplished. Thanks in advanced.

**Comment by engemasa** [comment]
...To be more specific, I'm looking to apply the ui-mask on the input of the datepicker-popup so that a user can enter a date manually (via the keyboard) and the mask will not only indicate the basic "format" expected ( __/__/____ ), but will ALSO restrict the input (numeric values).

**Comment by PowerKiKi** [comment]
I don't do much work on this project anymore, but @lukepfeiffer10 may be able to help you...

**Comment by lukepfeiffer10** [comment]
@engemasa The more recent versions of this library should work in conjunction with the datepicker directive with a small caveat. I believe if you use `space` as the placeholder character then you could run into some goofy situations.

Wanting the input to be restricted by the `ui-mask` is a different thing altogether and I'm fairly certain would not work for your use case. I would recommend letting the datepicker throw an invalid date error or use `ng-pattern` too.

**Comment by engemasa** [comment]
Thank you @lukepfeiffer10 .

**Comment by patlv23** [comment]
I would just like to post this to illustrate the issues I've been having:
https://plnkr.co/edit/0Vr5YRVREIT5EMu1m55z?p=preview

Basically seems to be a disconnect on the data the "picker" component references as opposed to the value itself.

**Comment by edriang** [comment]
@patlv23 Look at this edited plnkr: [https://plnkr.co/edit/DSM7JNqnRMgDULmfoZEb?p=preview](url)

I did some modifications to "Case 1" example:
- Added slash to uib-datepicker-popup="dd/MM/yyyy" to match ui-mask="99/99/9999" mask format
- Added the following attribute  model-view-value="true" that is an option from ui-mask directive

In this way I get the mask working, input value linked to model, and model value reflected to datepicker calendar.

(Let me know if this works for you too. I'm using last version of ui-bootstrap datepicker-popup)

**Comment by patlv23** [comment]
@edriang weird thing, I tried out your plunk but it doesn't seem to have any difference to my original

BUT...

I tried out the changes you mentioned and it seems to be working. Many thanks!

**Comment by feonit** [comment]
"https://plnkr.co/edit/DSM7JNqnRMgDULmfoZEb?p=preview"
that link dos not work already 

need some solution here

**Comment by patlv23** [comment]
@feonit I made changes to my original plunk, it works there
