### ISSUE TITLE
bad cursor placement

### ISSUE THREAD

**Issue by fabioginzel** [angular-ui/ui-mask#21]
Error https://github.com/angular-ui/ui-utils/issues/189
keeps happening

**Comment by maqeelqureshi** [comment]
facing same issue in windows phone 8.1

**Comment by PowerKiKi** [comment]
It seems it should now be solvable via #26, see the PR for explanation

**Comment by msimpson** [comment]
@PowerKiKi 
If you're going to continually answer issues relating to the input event on various mobile environments/keyboards with PR #26, then just add it to the README as a workaround already.
