### ISSUE TITLE
More funky placeholder behavior

### ISSUE THREAD

**Issue by wiltzius** [angular-ui/ui-mask#25]
I use this directive three places in our code, and unfortunately no invocation of the placeholder / ui-mask /ui-mask-placeholder attributes seem to work for all of them.

```<input ui-mask="(999) 999-9999" ng-model="x" placeholder="(555) 555-5555" ui-mask-placeholder/>```

```<input ui-mask="99/99/9999" ng-model="y" placeholder="MM/DD/YYYY" ui-mask-placeholder/>```

```<input ui-mask="(999) 999-9999" ng-model="z" placeholder="Phone number" ui-mask-placeholder/>```

None of these actually allow you to input text, sadly -- it gets stuck.

Removing the ui-mask-placeholder makes the MM/DD/YYYY placeholder work, surprisingly enough, but the other two for phone numbers are both broken (typing yields a mish-mash of the original placeholder text and the input text).

Am I using the new ui-mask-placeholder directive wrong? I copied the pattern from the demo.html page.

**Comment by dimrsilva** [comment]
The `ui-mask-placeholder` attr can be used to maintain the original placeholder behavior.

That said, from the three examples, only on third one is used correctly.

You should use:

`<input ui-mask="(999) 999-9999" ng-model="x" placeholder="(555) 555-5555" ui-mask-placeholder/>`
`<input ui-mask="99/99/9999" ng-model="y" placeholder="MM/DD/YYYY" ui-mask-placeholder/>`
`<input ui-mask="(999) 999-9999" ng-model="z" placeholder="Phone number" ui-mask-placeholder/>`

Anyway, your third example should work. So, there is a bug with empty placeholders.

On this plunk you can see a (not so good) workaround for this problem: http://plnkr.co/edit/gxQ2LJgQQuAjY9wtNvx8?p=preview

I'll try to fix this and do another PR asap.

**Comment by wiltzius** [comment]
Thanks for following up!

Sorry if I seem thick, but what is the difference between the version you posted and the version I posted for the first two examples? I think they are the same? I copy/pasted wrong when I first posted this issue and immediately edited to correct it, so perhaps you caught the first incorrect version -- sorry about that.

I'll look at the plunker now.

**Comment by wiltzius** [comment]
Ah, I see now in the plunker that I am indeed using the directive wrong entirely.

I copied the example from demo.html, which does not specify anything for the ui-mask-placeholder attribute it just includes it empty. Is that not a valid way to use it? In which case, I would be happy to update demo.html.

Lastly, in that plunker even with the workarounds it appears that neither of the phone number examples work quite right. Try typing "1234567890" -- by the time you're done typing it will read "(123) 467-8955". Or try typing "650" -- by that point it will suddenly switch to "605" instead. Very mysterious!

If more examples or test cases or something would help, happy to provide; or else let me know if there's some other way I can help. Thanks!

**Comment by dimrsilva** [comment]
My mistake, I just copy/paste and forgot to edit:

`<input ui-mask="(999) 999-9999" ng-model="x" ui-mask-placeholder="(555) 555-5555"/>`
`<input ui-mask="99/99/9999" ng-model="y" ui-mask-placeholder="MM/DD/YYYY"/>`
`<input ui-mask="(999) 999-9999" ng-model="z" placeholder="Phone number" ui-mask-placeholder/>`

**Comment by dimrsilva** [comment]
I got that too, there is a bug when you type the same key as on placeholder.

**Comment by wiltzius** [comment]
awesome, thank you for the corrections and for the fixes. It looks like now the latter two examples work, but the first one still has the issue where typing the same key as what's in the placeholder messes it up. I'll open a separate issue for that.

**Comment by SimSot** [comment]
@dimrsilva good day man, your workaround...if the mask is (555) 555-5555, I can't enter the digit 5. Please help.
