### ISSUE TITLE
ui-mask does not play nicely with other directives

### ISSUE THREAD

**Issue by peterox** [angular-ui/ui-mask#33]
If a directive has a higher priority than ui-mask and therefore modifies the model value in it's formatter before ui-mask's formatter is executed, changing the mask dynamically does not respect the other directive. Instead ui-mask 'masks' the model value directly, NOT the value returned from the other directives formatter.

**Comment by Tim91084** [comment]
You mean changing the mask via a dynamic binding like in the example below?

```ui-mask="{{maskBinding}}"  ```

**Comment by peterox** [comment]
That's right. Checkout the test in 9c59df9904edff2b1de0de2ea7a17315b991a3bb

**Comment by lukepfeiffer10** [comment]
@peterox Should this be closed? It appears to be working properly as the test you added is passing.
