### ISSUE TITLE
Mask conflicts with ng-messages when invalid/valid

### ISSUE THREAD

**Issue by blake-nouribekian** [angular-ui/ui-mask#42]
Suppose you had the following code for a phone number below where you are using ng-messages to display an error message saying that the field is required. If you type a phone number in and then delete the exact amount of numbers that you input you will see the "Required" message but if there are no numbers in the input and you hit the delete button again, the error messages will never come back even if you type numbers in the input and then delete them again. Not sure if this sounds confusing but its easy to replicate.
```
<div class="col-md-4">
		<label for="phone">
			<span class="required">*</span>&nbsp;Phone
			<span ng-messages="form.phone.$dirty && form.phone.$error" role="alert">
				<span ng-messages-include="error-messages"></span>
			</span>
		</label>
		<input type="text" class="form-control" name="phone" ng-model="formData.users.phone" model-view-value="true" ui-mask="(999) 999-9999" placeholder="(###) ###-####" ng-required="true">
	</div>


<script type="text/ng-template" id="error-messages">
		<span class="error" ng-message="required">Required</span>
		<span class="error" ng-message="email">Not a valid email address</span>
		<span class="error" ng-message="minlength">Field is too short</span>
		<span class="error" ng-message="maxlength">Field is too long</span>
		<span class="error" ng-message="min">Value is too small</span>
		<span class="error" ng-message="max">Value is too large</span>
	</script>
```

**Comment by alexw23** [comment]
Can you make a plunkr?

**Comment by blake-nouribekian** [comment]
What is strange is that I am not able to replicate the issue I am having on my site but I included the link anyways and I will see if I can play with it some more.

http://plnkr.co/edit/Jj4MtloejRDDPQxwDIcH?p=preview

**Comment by blake-nouribekian** [comment]
We can close this now as it seems to be fixed using the newest version
