### ISSUE TITLE
On Samsung Tablet the input is reversed

### ISSUE THREAD

**Issue by StarpTech** [angular-ui/ui-mask#44]
e.g my mask is `*-******-*?*` when I enter 3 digits:
`Z-21`instead `Z-12`
Do you have any ideas? Thanks!

**Comment by lukepfeiffer10** [comment]
If you refer to #21 and #26, those should fix your problem. In specific, if you remove the 'input' event (for only Android browsers) you should notice the problem go away.

**Comment by PowerKiKi** [comment]
Closing since @lukepfeiffer10 gave a workaround
