### ISSUE TITLE
Can't pass regular expression for maskDefinitions  via ui-options

### ISSUE THREAD

**Issue by mikhailmelnik** [angular-ui/ui-mask#45]
There are two issues I met so far:

1) `scope.$eval('[' + iAttrs.uiOptions + ']');` can't parse regular expressions stated directly in HTML
2) if I use scope to define ui-options, custom `maskDefinitions` got overridden by `angular.extend(current[i], original[i]);`

Are they real issues or I'm just doing something wrong? Is there any working example how to use ui-options to override default regexes?

**Comment by Tim91084** [comment]
Looks like a legitimate issue.  Started a plunkr to demonstrate.  Check out the console output.

http://plnkr.co/edit/zbFZp2FO3HPibkzwPspP?p=preview

**Comment by suman-mits** [comment]
+1 Is this issue resolved? I am stuck at this now

**Comment by PowerKiKi** [comment]
@suman-mits the PR #60 is waiting for tests to be merged

**Comment by PowerKiKi** [comment]
Fix released in 1.5.1, thanks @Tim91084 !
