### ISSUE TITLE
Tests fail in IE 9-11

### ISSUE THREAD

**Issue by NickTomlin** [angular-ui/ui-mask#5]
Running the tests with sauce (or against local VMs) results in the following failing specs: 

![screen shot 2015-07-02 at 5 24 33 pm](https://cloud.githubusercontent.com/assets/1290336/8489284/880a34d4-20df-11e5-8acf-56dd6524149f.png)

I'd be happy to help troubleshoot this if you have any ideas on where to start with the mask code. Also, getting these tests running on CI would be great (happy to help set that up as well, if you have an open source Sauce account).

**Comment by PowerKiKi** [comment]
Thanks for reporting. I am unfortunately not familiar with ``ui-mask`` codebase, nor sauce. But ``ui-mask`` quality and reliability could clearly be improved. There were a lots of reported bugs in previous repository for ``ui-mask``.

So if someone would step up and take a few initiative on that project, that would probably be very welcome by its users. But I'm afraid this won't be me. I will merge PR, but can't do much more than that.

**Comment by NickTomlin** [comment]
Thanks for the response! I am using an older version of ui-mask and would love to see it more actively maintained. I'll see if I can find some time to help make improvements. Is there an IRC channel/community for the `ui-*` components? Thanks again for you willingness to review and respond to issues/prs.

**Comment by PowerKiKi** [comment]
Not sure about IRC, but we could try to actually use https://gitter.im/angular-ui. I know ui-grid is quite active on Gitter. I guess that would be nice if the organisation itself got some activity too...

**Comment by PowerKiKi** [comment]
Mhh... I just noticed that organisation rooms are private only on Gitter. So maybe we could create a room only for ui-mask ? I'll check with others what they think of that ...

**Comment by PowerKiKi** [comment]
We now have https://gitter.im/angular-ui/ui-mask available if you want to chat about ui-mask...

**Comment by lukepfeiffer10** [comment]
It appears that the `input.triggerHandler("input")` in some if not all of the tests on IE does not actually trigger the `eventHandler` function. I haven't been able to find anything conclusive about why this might be happening from a Google search.

I believe changing `input.triggerHandler("input")` to `input.triggerHandler("change")` will make the tests pass on IE but I'm not sure if that is necessarily something we want to do as this might be a bigger issue that needs to be fixed.
