### ISSUE TITLE
How to make ui-mask retain the invalid input when focus is lost?

### ISSUE THREAD

**Issue by lucasjs** [angular-ui/ui-mask#50]
Hey my friend!
Love the ui-mask, but I have this big problem.
Can you help me?

**Comment by NickTomlin** [comment]
From the [README](https://github.com/angular-ui/ui-mask#customizing): 

> You can customize several behaviors of ui-mask by taking advantage of the ui-options object. Declare ui-options as an additional attribute on the same element where you declare ui-mask.

> Inside of ui-options, you can customize these three properties:

> clearOnBlur - default: true

You want to set `clearOnBlur` to false

**Comment by lucasjs** [comment]
o rly? that's so easy and I spend hours seachirng on google LOL
thanks buddy.

**Comment by NickTomlin** [comment]
@lucasjs not a problem :) . Could you please close this issue?

**Comment by lucasjs** [comment]
@NickTomlin sure! thnks
