### ISSUE TITLE
Request: option to not unmask

### ISSUE THREAD

**Issue by kmaida** [angular-ui/ui-mask#52]
I'd really like to have the masking available to aid the user, but then would also like to save/submit the value as the masked value and not unmask it.

Would it be possible to have an option for this added in the future?

**Comment by nshahpazov** [comment]
+1

**Comment by Tim91084** [comment]
Have you tried model-view-value="true"?

**Comment by simoncowie** [comment]
Yeah, ~model-view-value="true"~ works for this. Documentation needs a bit of work to show this I think.

**Comment by PowerKiKi** [comment]
@simoncowie PR are more than welcome to improve docs or anything else.
