### ISSUE TITLE
masked input inside ng-if uses incorrect placeholder

### ISSUE THREAD

**Issue by derekmt12** [angular-ui/ui-mask#58]
When a masked input is inside of ng-if, ng-switch, or any directive that creates a copy of the current scope, it initially shows the ui-mask-placeholder instead of the placeholder value. After the input gains focus and then loses focus, the placeholders perform correctly.

Here is a plunk demonstrating the issue:
http://plnkr.co/edit/mMRgmfQRJjWBeA1YmOYg?p=preview

**Comment by Tim91084** [comment]
well, I can see why it's happening.  When the mask is within the ng-if, `initPlaceholder` runs after the formatter.  The formatter seems to be what is allowing the placeholder attribute to take precedence.  Anyhow, here's a potential fix - not sure of the implications of this one though....  Add this within `initPlaceholder` : `&& !(iAttrs.placeholder && !controller.$modelValue)`


    function initPlaceholder(placeholderAttr) {
      if ( ! placeholderAttr) {
        return;
      }

      maskPlaceholder = placeholderAttr;
      // If the mask is processed, then we need to update the value
      if (maskProcessed && !(iAttrs.placeholder && !controller.$modelValue)) {
        iElement.val(maskValue(unmaskValue(iElement.val())));
      }
    }

**Comment by lukepfeiffer10** [comment]
@Tim91084 Have you tried implementing this fix and running the tests? Not saying that would give 100% certainty there aren't side effects with the code but it would be somewhere to start.
