### ISSUE TITLE
Mask date format

### ISSUE THREAD

**Issue by hebbian** [angular-ui/ui-mask#61]
How to mask a date format? If I set the mask to 99/99/9999, you can input number with max 9, and I found that ui-mask execute on each character, what about if I want to limit max value from 1-31, or month to 1-12 as a date format should be?

**Comment by PowerKiKi** [comment]
This is not possible with ui-mask, instead use `<input type="date">`, or another custom component, such as https://github.com/angular-ui/bootstrap or https://github.com/angular-ui/ui-date

**Comment by omarmeky** [comment]
You can use a dynamic placeholder to accomplish this. For example (for a valid month):

```
$scope.options = {
    allowInvalidValue: true,
    maskDefinitions: {a: /[01]/, b: /[1-2]/, c: /[1-9]/}
};

<input ng-model="dob"
            ng-model-options="{ allowInvalid: true }"
            ui-mask="{{dob.substring(0, 1) === '1' ? 'ab' : 'ac'}}"
            ui-options="options"
            model-view-value="true">
```
