### ISSUE TITLE
Format of ui-options

### ISSUE THREAD

**Issue by cjfringe** [angular-ui/ui-mask#67]
Can we please see an example of ui-options? Specifically, maskDefinitions? When I try to add ui-options to a form field I am getting an error.
```Uncaught TypeError: n[0].test is not a function```

The form field I have looks like this.
```
    <input id="dob" type="text" data-ng-model="vm.dob" placeholder="Date of Birth" name="dob" data-ui-mask="19/39/2999" data-ui-mask-placeholder="" data-ui-mask-placeholder-char="_" data-ui-options="{maskDefinitions: { '1':'/[0-1]/', '2':'/[0-2]/', '3':'/[0-3]/' } }" required="required">
```

Any help would be appreciated.

**Comment by savokiss** [comment]
You'd better remove the `'` from the regular expression and defined the options in the scope.
like this:
controller
```
$scope.maskOptions = {
maskDefinitions: 
    { '1':/[0-1]/, '2':/[0-2]/, '3':/[0-3]/ } 
}
```
HTML:
```
ui-options = "maskOptions"
```
