### ISSUE TITLE
Problems with pasting in values

### ISSUE THREAD

**Issue by zorzysty** [angular-ui/ui-mask#71]
UI-Mask does not behave as expected when pasting values into input.
This is how to recreate the issue:

**Scenario 1**
1. Enter value "by hand"
2. Select whole value
3. Paste different value to the input field

Expected behaviour:
Previous value is replaced.

Current behaviour:
Previous value is not replaced.

**Scenario 2**
1. Enter part of the value
2. Set cursor at the beggining
3. Paste some value

Expected behaviour:
Pasted value is inserted where cursor was pointing

Current behaviour:
Pasted Value is inserted at the end of the initial value disregarding cursor position

**Comment by lukepfeiffer10** [comment]
After looking at the code and doing a couple of tests, it seems like this issue can easily be resolved by removing the `onPasteHandler`.

However, maybe someone else is aware of the reason that handler is there in the first place. It doesn't seem to be doing much; except of course causing this issue as the code explicitly sets the cursor position at the end of the value. Interested in hearing someone else's input on this issue.
