### ISSUE TITLE
I am using ui-mask and the value for 9 gets replaces for all number 1-9(digits). how can i just restrict mask to have only 9 as a value

### ISSUE THREAD

**Issue by vizart87** [angular-ui/ui-mask#72]

**Comment by PowerKiKi** [comment]
See 'maskDefinitions' in Readme

**Comment by vizart87** [comment]
maskDefinitions are not getting overridden i want to override 9 for numerical digit [9]. CAn you provide with example.

**Comment by PowerKiKi** [comment]
Did you try `{ '9': /9/}` ?

**Comment by ProgressoRU** [comment]
I have same issue.
This is my view:
```html
<input class="form-control" id="t1" ui-options="vm.mask" name="phone" maxlength="20" ui-mask="{{vm.current.phoneFormat}}" model-view-value="true" ng-model="vm.selected.phone_first">
```
This is phone format:
```
+996NN NNN-NN-NN
```
And mask definition:
```js
            vm.mask = {
                maskDefinitions: {
                    'N': /\d/, '#': /\d/, 'A': /[a-zA-Z]/, '*': /[a-zA-Z0-9]/
                }
            };
```
In result input looks like this: ![Input](http://i.imgur.com/o8KuWg0.png)

With ``{ '9': /9/}`` added to maskDefinitions, as proposed above, is still the same, but only `9` will be available to enter in the place of first 2 characters.

Sorry for my poor English, I hope my explanation is understandable.

**Comment by vizart87** [comment]
I did work around for the problem i over write the uiMaskConfig in app.js
.value('uiMaskConfig', {
        maskDefinitions: {
            'N': /\d/,
            'A': /[a-zA-Z]/,
            '*': /[a-zA-Z0-9]/
        },
        clearOnBlur: false,
        eventsToHandle:  ['input', 'keyup', 'click', 'focus']
    });

**Comment by z0rbas** [comment]
This still seems to be a problem. vizart87's workaround works. I needed a hardcoded 'A' in the mask and was unable to add it.

**Comment by lukepfeiffer10** [comment]
It's not really a workaround, more like intended functionality. The `maskDefinitions` object specifies how you can define the mask. Each key maps to a regex that specifies the requirements for the character at each position. So, having `A` in a mask says any alphabetic character (upper or lower case) is permitted. If you need to have `A` as a static value in the mask, then you need to override the `maskDefinitions` object and replace the `A` key with some other value.

**Comment by z0rbas** [comment]
I did RTFM, but I wasn't able to use ui-options to enable using 'A' as a static character. It seems easy enough but it didn't work ...
Are you able to pull this off?

Thanks!

**Comment by z0rbas** [comment]
I looked at the issue again and voila. If a character has already been defined, one needs to disable it with: ui-options="{ maskDefinitions: { 'A': undefined } }". This didn't seem obvious to me.

Thanks for sending me back to the drawing board.

**Comment by lukepfeiffer10** [comment]
Yeah after commenting earlier I was thinking how you would go about undefining something in the default `maskDefinitions` and I guess that is probably the only way to do it on an individual level... Not sure that could be changed either without making breaking changes to the directive.

On a global scope, you could obviously just redefine the entire object but I don't know if that is a good solution for what you are doing.

**Comment by NDurham12** [comment]
@z0rbas , I'm not able to get the disable to work property. 

When I use the Mask: ui-mask="1AA89010dddddddddddddddddddddd"
and the UI Options : ui-options="{ maskDefinitions : { 'A': undefined} }"
I get placeholders : placeholder="1__8_010dddddddddddddddddddddd" in my output.  So the '_' are where the 'A' is still be replaced.  

what could I be missing here? Seems so simple but I have not been able to get it to work.
