### ISSUE TITLE
Global Configuration

### ISSUE THREAD

**Issue by julianomqs** [angular-ui/ui-mask#74]
It will be nice if ui-mask have global configuration, e.g

```
angular
    .module('x-module')
    .config(config);

function config(UiMaskProvider) {
    UiMaskProvider.setPlaceholderChar('space');
    // another configurations
}
```

Then every input with `ui-mask` will use space as char.

Thanks.

**Comment by flyer1** [comment]
I updated global ui mask config like this. Does this work?

    function config(uiMaskConfigProvider) {
        var maskDefinitions = uiMaskConfigProvider.$get().maskDefinitions;
        // Update the mask definitions to support uppercase/lowercase masks
        angular.extend(maskDefinitions, {
            'a': /[a-z]/,
            'A': /[A-Z]/
    });
