### ISSUE TITLE
Weird value when using placeholder

### ISSUE THREAD

**Issue by sean-hill** [angular-ui/ui-mask#75]
Here's my HTML:

	<input type="text" ng-model="form.phoneNumber" placeholder="Phone Number" ui-mask="(999) 999-9999" ui-mask-placeholder ui-mask-placeholder-char class="form-control">

Here's before focus:

![screen shot 2015-11-19 at 11 45 42 am](https://cloud.githubusercontent.com/assets/1205866/11280448/5377d112-8eb3-11e5-870f-795c123b7678.png)

Here's when focused:

![screen shot 2015-11-19 at 11 45 45 am](https://cloud.githubusercontent.com/assets/1205866/11280466/5d33369c-8eb3-11e5-996e-45531cfdf2f6.png)

Here's when typing:

![screen shot 2015-11-19 at 11 48 06 am](https://cloud.githubusercontent.com/assets/1205866/11280482/6cd40978-8eb3-11e5-8494-dbbe60e89ca5.png)

What am I doing wrong? The documentation isn't very clear about how to use placeholders, I just copied the code from the demo.

**Comment by ZeRego** [comment]
+1 same problem here

**Comment by lukepfeiffer10** [comment]
Have you tried updating your version of ui-mask?

This might have been an issue related to #25 that was fixed partially by #27. At least the issues with having empty `ui-mask-placeholder`.

**Comment by sean-hill** [comment]
@lukepfeiffer10 I have the latest version as of 6 days ago. The latest release was 11 days ago.

**Comment by lukepfeiffer10** [comment]
@sean-hill Can you provide a plunkr that recreates and shows the issue?

**Comment by tgiacchi** [comment]
Same problem.  Specifically, see code below.  When typing in a number into the phone number mask, if you type numbers 0-8 everything is okay.  It messes up when you type a '9'.  It seems to almost be treating it like an incorrect character and it loses it's place in the mask.

<input class="form-control" ng-model="number" ui-mask='999  ui-mask-placeholder=' 999' type="text">

This is the simplest test you can work with I think

**Comment by sean-hill** [comment]
Hey @lukepfeiffer10 I just made a plunkr with only angular and the mask libraries included [here](http://plnkr.co/edit/aAe5SHxgBjEuapA0mxNZ?p=preview). It appears that the bug is fixed is this situation. I wonder if it's another library that may be conflicting. I also have `ui.bootstrap` included in my project. Maybe that might be an issue?

**Comment by tgiacchi** [comment]
If the placeholder character is a ‘9’ (even in the demo on github) the problem shows up.

**Comment by lukepfeiffer10** [comment]
@tgiacchi you are experiencing the same issue as #32. Here is the plunkr from that issue that should solve your problem, [link](http://plnkr.co/edit/HPIGBouGjO7goSTGI7A0?p=preview). However, that solution hasn't been incorporated into a release at the moment. 

@sean-hill I can't be 100% certain that including `ui.bootstrap` is causing your problem although I can say that I am successfully using both `ui.mask` and `ui.bootstrap` in the same angular app. Do you pre-populate your model value that is binding to the text box you have the mask on (not sure if this could even be an issue but something to look into perhaps)?
