### ISSUE TITLE
Need masking without the validation

### ISSUE THREAD

**Issue by pheintzelman** [angular-ui/ui-mask#78]
We want to use this library but have our own validation. It would be awesome if there was an option to not set validity. Also in our case we want the model to be updated with the partially complete value this would also be a great setting.

**Comment by PowerKiKi** [comment]
You're gonna have to submit a patch if you want any kind of improvement for this project.

**Comment by pheintzelman** [comment]
(?9?9?9) ?9?9?9-?9?9?9?9 will work for me for now thanks. Unfortunately contributing to this library is not clear cut given policies at my workplace.

**Comment by lukepfeiffer10** [comment]
The new option `allowInvalidValue` should handle this now.

**Comment by MAbdulHalim** [comment]
just add "?" like `ui-mask="(?9?9?9) ?9?9?9?9-?9?9?9?9" `
