### ISSUE TITLE
Save invalid data in model

### ISSUE THREAD

**Issue by corehook** [angular-ui/ui-mask#80]
Hi dudes! I want to save invalid data in model ( for notification user that he input invalid phone number for example ), but i cant because user.phone_number empty and i cant check that field filled by user  or keep it empty ( not entered anything ).

```coffee
%input{:type => "text", 'ng-model' => 'user.phone_number',  'ui-mask' => "+9 (999) 999-99-99", 'ui-options' => "{clearOnBlur : }"}/
```

clearOnBlur store entered data in input but in user model i didnt see phone_number field.

**Comment by lukepfeiffer10** [comment]
Not entirely certain what kind of user notification you are looking for when entering invalid data, but the input should have the class `ng-invalid` when the input is invalid. Using that you should be able to create some sort of css style to notify the user of invalid input.

**Comment by corehook** [comment]
@lukepfeiffer10 thanks!
