### ISSUE TITLE
CHANGELOG.md

### ISSUE THREAD

**Issue by kcaron-cst** [angular-ui/ui-mask#81]
Wondering if there is a changelog for tagged releases. Much easier to maintain packages in larger projects if potential breaking changes can be quickly identified. Haven't updated since 1.4.6

Comparing the [readme file](https://github.com/angular-ui/ui-mask/compare/1.4.6...1.6.2), looks like there are several breaking changes, is this correct?

**Comment by lukepfeiffer10** [comment]
Honestly I don't think there were any breaking changes. Only new functionality and bug fixes.

Not that a changelog is a bad idea I just don't think you should have any issues getting the latest version.

**Comment by kcaron-cst** [comment]
Thanks @lukepfeiffer10

**Comment by PowerKiKi** [comment]
@lukepfeiffer10 is right here. No intentional BC and no changelog available except the commit messages. The reason beeing a serious lack of manpower to manage that.
