### ISSUE TITLE
ng-required - Model does not binding on its value

### ISSUE THREAD

**Issue by RenatoRC** [angular-ui/ui-mask#84]
When I set an input text with ng-required and I don't specific a mask, the model does not binding on its value.

I've created a plunker.
http://plnkr.co/edit/kq2baWdgemcuYp0dxSu4?p=preview

**Comment by cleever** [comment]
+1

**Comment by lukepfeiffer10** [comment]
@RenatoRC I guess I just don't see the use case here. Why are you using ui-mask if you aren't specifying a mask for it to use?

**Comment by cleever** [comment]
@lukepfeiffer10 The primary use case for this scenario is when you need to set mask dynamically.

**Comment by RenatoRC** [comment]
Exactly. I need to set mask dynamically.
