### ISSUE TITLE
main: dist/index.js is lacking 

### ISSUE THREAD

**Issue by okhomenko** [angular-ui/ui-mask#85]
Looks like gulp remove dist/index.js file which is required in package.json as main. 

Now it is broken as CommonJS dependency

**Comment by okhomenko** [comment]
I guess you published to npm something other than checked in as 1.6.4

**Comment by fcaballero** [comment]
+1

**Comment by dhaspden** [comment]
Same problem

**Comment by keithbranton** [comment]
Looks like the index.js file added in https://github.com/angular-ui/ui-mask/commit/f395088b353a725f06746516cba65236bad2d1e4 should probaly have been added to the src folder, not the dist folder?

**Comment by PowerKiKi** [comment]
Fixed in #88
