### ISSUE TITLE
ui-mask stops working after running through $compile

### ISSUE THREAD

**Issue by boroth** [angular-ui/ui-mask#89]
I have a directive that's adding a name attribute to input elements that don't have a name attribute. In order for these new names to be caught by the FormController, I have to recompile the element after adding the name.  However, after it's compiled you can no longer enter text into the input field.

Plunker [here](http://plnkr.co/edit/BLEmSad6FCA9tC8JJz2k?p=preview).

The plunk shows two directives, one which compiles, the other that doesn't. 

I'm looking into reasons why this might be happening, but wanted to post the issue to see if anyone comes up with any ideas while I'm looking at it.

**Comment by lukepfeiffer10** [comment]
@boroth Have you tried to make sure your directive that recompiles the element runs first?

**Comment by boroth** [comment]
It probably has something to do with the directive being applied twice (because of the double compile?).

My directive definitely runs first, but then it gets run again (each directive runs twice).

**Comment by boroth** [comment]
I think I figured it out! I got around calling $compile() by updating the formController and ngModelController manually (see below).

```
MY.directive('input', function($compile) {
    return {
        restrict: 'E',
        require: ['?^^form', '?ngModel'],
        replace: false,
        priority: 1500,
        compile : function () {
            return {
                pre : function(scope, element, attrs, controllers) {
                    var formController = controllers[0];
                    var ngModelController = controllers[1];

                    if (!attrs.autocomplete) {
                        element.attr('autocomplete', 'off');
                    }

                    if (!attrs.name) {
                        element.attr('name', attrs.ngModel);

                        if (formController && ngModelController) {
                            ngModelController.$name = attrs.ngModel;
                            formController.$removeControl(ngModelController);
                            formController.$addControl(ngModelController);
                        }
                    }
                }
            };
        }
    };
});
```

I'll close this out as the issue isn't with ui-mask per-se; however, is it normally frowned upon to recompile an element that has additional directives? Just asking for future reference.

**Comment by lukepfeiffer10** [comment]
Glad you found a solution to your problem.

Also, I have no idea about the multiple compilation. I assume it's not a best practice though as the compile and link steps are just single passes.

Just a thought but doesn't the pre-compile function have access to the original element (sometimes referred to as the template element)? If it does shouldn't you just be able to add the name element to the template element and then the normal compile process should pick it up?

**Comment by boroth** [comment]
Hmmm, I tried replacing the `element` with a cloned element with the added name, but when I re-added it I assumed that I had to still re-compile, so it was still broken. I didn't try replacing without re-compiling.

**Comment by lukepfeiffer10** [comment]
Have you tried `element.prop('name', 'blah')` on the template element? Might not even need to clone and replace.
