### ISSUE TITLE
how can i set mask for money

### ISSUE THREAD

**Issue by davidwillianx** [angular-ui/ui-mask#92]
I would like to do something like this >> 
9,90
90,90
9.900,99
etc>>

does ui-mask able to do?

**Comment by lukepfeiffer10** [comment]
I don't think ui-mask has the functionality you are looking for as there isn't a way to specify one or more of some value like you need to for currency. My best guess would be to create a directive with a custom `$formatter` that runs the angular currency filter on the value input by the user.

**Comment by davidwillianx** [comment]
pretty cool! thx dude it helps a lot :+1:
