### ISSUE TITLE
Defining a mask for SSN

### ISSUE THREAD

**Issue by johnmanko** [angular-ui/ui-mask#94]
I'm trying to define a mask that will work to display the mask but allow entry of just numbers.

// I only have the last four of the ssn
`ssn = "6789"`
or
`ssn = "*****6789"`

`                        <input type="text"
                               ng-model="ssn"
                               ui-mask="*****9999"  
                               ui-mask-definitions="{ '9': /\d/, '*': /[\*0-9]/ }"
                               ui-mask-placeholder 
                               ui-mask-placeholder-char="_"/>
`
The data doesn't display.

If I do the following I can't edit the first 5 characters:

`ssn = "#####6789"`

`                        <input type="text"
                               ng-model="ssn"
                               ui-mask="#####9999"  
                               ui-mask-definitions="{ '9': /\d/, '#': /[#0-9]/ }"
                               ui-mask-placeholder 
                               ui-mask-placeholder-char="_"/>`

I really want to allow only numeric to be entered, but ALWAYS hide the first 5 characters with the mask character.

**Comment by lukepfeiffer10** [comment]
I am pretty sure the functionality you are looking for is not included in this library. The library doesn't "hide" characters it just displays to the user how the input should look and assists in entering that input properly.

If you need to hide characters you are best off using a custom `$formatter`. Something that takes your model value and then replaces the first five characters with a special "hidden" character of your choosing.

**Comment by johnmanko** [comment]
ah, ok. Thanks.
