### ISSUE TITLE
"Module 'ui.mask' is not available" error on adding ui.mask to Onsen Mobile App

### ISSUE THREAD

**Issue by RezaRahmati** [angular-ui/ui-mask#95]
Hi

When I try adding ui.mask to my mobile project I get this error
rror: [$injector:modulerr] Failed to instantiate module ui.mask due to:
Error: [$injector:nomod] Module 'ui.mask' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

I use angular 1.4.7, and I don't use jquery. So I changed the demo file and it works fine but I still have the same error on Chrome.
Is there any other dependencies that I should include?

p.s I googled and I found two other people had the same problem with ionic, somebody says that add ui.util too, but it didn't work too.

**Comment by lukepfeiffer10** [comment]
Are you sure that the `ui-mask` module is being correctly added to your application module or the Onsen module?

**Comment by egdraper** [comment]
There is a "!" at the beginning of the minified mask.min.js file, which is breaking the code. It took us over an hour to realize where the problem was. Simply remove the "!" and it should work.

**Comment by Tim91084** [comment]
I see the exclamation point, but, it's been there for a little while - https://github.com/angular-ui/ui-mask/blob/84ef9137a40f24936ac9fc13722a143d42bf9dee/dist/mask.min.js

**Comment by vvsatpute** [comment]
You may refer this file. https://cdnjs.cloudflare.com/ajax/libs/angular-ui-mask/1.8.7/mask.js
