### ISSUE TITLE
Keep invalidated data on blur, but clear it if it's empty.

### ISSUE THREAD

**Issue by burakicel** [angular-ui/ui-mask#99]
I know you can keep invalidated data with ui-options="{clearOnBlur:false}", but if the textbox is empty, this leaves a blank mask. Is it possible to show the placeholder if it's empty ?

Let's say ui-mask="+9 (999) 999-9999", and placeholder="Phone". I want to keep a user's incomplete number but show "Phone" if they have no number input when they blur. Thanks

**Comment by lukepfeiffer10** [comment]
Is the functionality in this [plunkr](http://plnkr.co/edit/4tl83vhZQL3KLzXJjjph?p=preview) what you are trying to get?

**Comment by burakicel** [comment]
Yes, exactly what I was looking for. I will look into it. Thanks!

**Comment by lukepfeiffer10** [comment]
Okay I'll try and get a PR for that change tomorrow. That was a quick, dirty, untested change in that plunkr just to check I understood you properly.
